[package]
name = "web3-mongo-types"
version = "1.0.0"
edition = "2021"
description = "A library for converting Ethereum transaction receipts from web3 to MongoDB BSON documents"
license = "MIT"

[dependencies]
mongodb = "3.1.1"
web3 = "0.19.0"
ethereum-types = "0.15.1"
hex = "0.4.3"